export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";

// USER ACTION TYPES
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

// USER SEARCH ACTION TYPES
export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";
export const CLEAR_USER_SEARCH = "CLEAR_USER_SEARCH";
